### PR TITLE
My modifications

### PR DESCRIPTION
**Pull request by linev**
I create several examples.
Two require.js variants and standalone.
I am not sure if one really need external libraries dependency in bower.json - especially three.js.
It is huge and takes a lot of time.

I recommend to use standalone examples.

### CODE REVIEW

**Comment by mvala** [comment]
By the way index_require_extern.html is not working

**Comment by linev** [comment]
I need to check it.
I remove all dependency from bower.json, probably it has side effect.
Later today I will try it.

**Comment by mvala** [comment]
Yes it is, I removed vendor directory and after installation

```
[mvala@vala vendor]$ ls -al 
total 24
drwxrwxr-x. 6 mvala mvala 4096 Mar 11 10:40 .
drwxrwxr-x. 4 mvala mvala 4096 Mar 11 10:42 ..
drwxrwxr-x. 8 mvala mvala 4096 Mar 11 10:40 bootstrap
drwxrwxr-x. 4 mvala mvala 4096 Mar 11 10:40 jquery
drwxrwxr-x. 5 mvala mvala 4096 Mar 11 10:40 jsroot
drwxrwxr-x. 2 mvala mvala 4096 Mar 11 10:40 requirejs
```

**Comment by linev** [comment]
It depends that you have inside config.js file.
If it not updated, example will fail.

**Comment by mvala** [comment]
I see. I removed config.js. and after clean install it works

**Pull request merged**
